swagger: '2.0'
info:
  description: This is a RESTful API for immediate and scheduled rides
  version: "2.0"
  title: Ride Hailing Service API

paths:
  /get/event1:
    get:
      summary: get event1 based on an offset from the first event (passing 10 returns 10th event object)
      operationId: app.event1
      description: get event
      produces:
      - application/json
      parameters:
      - in: query
        name: offset
        description: Immediate ride request
        required: false
        type: integer
      responses:
        201:
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/requestImmediate'
        400:
          description: bad input, invalid object
  /get/event2:
    get:
      summary: get oldest event2 based on offset from first event
      operationId: app.event2
      description: get oldest event2
      produces:
      - application/json
      parameters:
      - in: query
        name: offset
        description: Immediate ride request
        required: false
        type: integer
      responses:
        201:
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/requestScheduled'
        400:
          description: bad input, invalid object
definitions:
  requestImmediate:
    type: object
    required:
    - id
    - name
    - location
    - destination
    - passengers
    properties:
      id:
        type: string
        format: uuid
        example: d290f1ee-6c54-4b01-90e6-d701748f0851
      name:
        type: string
        example: John Smith
      location:
        type: string
        example: 1234 Sesame Street
      destination:
        type: string
        example: 1234 Sesame Street
      passengers:
        type: integer
        example: 2
  requestScheduled:
    type: object
    required:
    - id
    - name
    - location
    - destination
    - passengers
    - datetime
    properties:
      id:
        type: string
        format: uuid
        example: d290f1ee-6c54-4b01-90e6-d701748f0851
      name:
        type: string
        example: John Smith
      location:
        type: string
        example: 1234 Sesame Street
      destination:
        type: string
        example: 1234 Sesame Street
      passengers:
        type: integer
        example: 2
      datetime:
        type: string
        format: date-time
        example: 2020-01-09T09:15:00.001Z